export const games = [
  {
    id: 1,
    type: 'casinos',
    name: 'Casino A',
    imgLink: './images/e1.png',
    percentage: '100%',
    "jusqu'a": "JUSQU'A",
    amount: '500€',
    spin_amount: 20,
    features: ["100% jusqu'à 500€", '20 free spins', 'Retraits rapides (24h)'],
    clr: '#530355',
    rating: './images/s1.svg',
    buttonLink: 'https://www.sos-casino.com/go/wildsultan',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/wild-sultan,',
    bgclr: '#edecf0',
    lancement: 2015,
    licence: 'Curaçao',
    depotmin: '20€',
    introduction: `Actif depuis 2015, Wild Sultan Casino a su convaincre de nombreux joueurs qui ne cessent d’en vanter les mérites.`,
    wagering: '35x', // Odd id
  },
  {
    id: 2,
    type: 'casinos',
    name: 'Casino B',
    imgLink: './images/e2.png',
    percentage: '150%',
    "jusqu'a": "JUSQU'A",
    amount: '300€',
    spin_amount: 25,
    features: ["150% jusqu'à 300", '25 free spins', 'Bonus sans wager'],
    clr: '#33776a',
    rating: './images/s1.svg',
    buttonLink: 'https://www.sos-casino.com/go/cresus',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/cresus',
    bgclr: '#ffffff',
    lancement: 2014,
    licence: 'Curacao',
    depotmin: '20€',
    introduction: `Si vous êtes à la recherche d'un casino en ligne fiable, Cresus Casino est une valeur sûre.`,
    wagering: '0x', // Even id
  },
  {
    id: 3,
    type: 'casinos',
    name: 'Casino C',
    imgLink: './images/e3.png',
    percentage: '150%',
    "jusqu'a": "JUSQU'A",
    amount: '500€',
    spin_amount: 100,
    features: ['500€ de bonus', '100 free spins', '10€ sans dépôt'],
    clr: '#882b80',
    rating: './images/s2.svg',
    buttonLink: 'https://www.sos-casino.com/go/magicalspin',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/magical-spin',
    bgclr: '#edecf0',
    lancement: 2017,
    licence: 'Antillephone',
    depotmin: '10€',
    introduction: `Un délai de retrait ultra rapide qui a fait l'unanimité auprès de notre communauté !`,
    wagering: '0x', // Odd id
  },
  {
    id: 4,
    type: 'casinos',
    name: 'Casino D',
    imgLink: './images/e4.png',
    percentage: '100%',
    "jusqu'a": "JUSQU'A",
    amount: '1000€',
    spin_amount: 365,
    features: ['Pack bonus 1 000€', '365 free spins', 'Bonus exclusif'],
    clr: '#222222',
    rating: './images/s3.svg',
    buttonLink: 'https://www.sos-casino.com/go/winoui',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/winoui',
    bgclr: '#ffffff',
    lancement: 2018,
    licence: 'Curaçao',
    depotmin: '10€',
    introduction:
      ' Le casino francophone Winoui s’impose petit à petit dans le paysage des jeux d’argent en ligne.',
    wagering: '20x', // Even id
  },
  {
    id: 6,
    type: 'casinos',
    name: 'Casino F',
    imgLink: './images/e6.png',
    percentage: '100%',
    "jusqu'a": "JUSQU'A",
    amount: '100€',
    spin_amount: 70,
    features: ['300€ de bienvenue', '290 free spins', 'Bonus sans wager'],
    clr: '#29253b',
    rating: './images/s3.svg',
    buttonLink: 'https://www.sos-casino.com/go/madnix',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/madnix',
    bgclr: '#edecf0',
    lancement: 2019,
    licence: 'Curaçao',
    depotmin: '20€',
    introduction: 'Welcome to Casino T!',
    wagering: '0x', // Odd id, updated
  },
  {
    id: 7,
    type: 'nouveauxCasinos',
    name: 'Casino G',
    imgLink: './images/e7.png',
    percentage: '150%',
    "jusqu'a": "JUSQU'A",
    amount: '200€',
    spin_amount: 100,
    features: ['200€ de bonus', 'Happy Hour', 'Cercle VIP'],
    clr: '#24282a',
    rating: './images/s2.svg',
    buttonLink: 'https://www.sos-casino.com/go/betzino',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/betzino',
    bgclr: '#ffffff',
    lancement: 2020,
    licence: 'Antillephone',
    depotmin: '20€',
    introduction: 'Welcome to Casino T!',
    wagering: '40x', // Even id, updated
  },
  {
    id: 8,
    type: 'nouveauxCasinos',
    name: 'Casino H',
    imgLink: './images/e8.png',
    percentage: '100%',
    "jusqu'a": "JUSQU'A",
    amount: '1000€',
    spin_amount: 50,
    features: ['1 000€ de bonus', '50 free spins', 'bonus exclusif de 150%'],
    clr: '#0f053d',
    rating: './images/s2.svg',
    buttonLink: 'https://www.sos-casino.com/go/x1casino',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/x1-casino',
    bgclr: '#edecf0',
    lancement: 2022,
    licence: 'Antillephone',
    depotmin: '10€',
    introduction: `Un petit voyage dans l'espace fort dépaysant en compagnie de X1 Casino !`,
    wagering: '40x', // Odd id, updated
  },
  {
    id: 9,
    type: 'casinos',
    name: 'Casino I',
    imgLink: './images/e9.png',
    percentage: '100%',
    "jusqu'a": "JUSQU'A",
    amount: '500€',
    spin_amount: 100,
    features: ["100% jusqu'à 500€", '100 free spins', 'Cashback VIP'],
    clr: '#df6763',
    rating: './images/s2.svg',
    buttonLink: 'https://www.sos-casino.com/casinos/madnix',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/stakes',
    bgclr: '#ffffff',
    lancement: 2016,
    licence: 'Antillephone',
    depotmin: '10€',
    introduction:
      'STAKES a réussi à se démarquer en très peu de temps auprès de notre communauté de joueurs.',
    wagering: '20x', // Even id, updated
  },
  {
    id: 10,
    type: 'casinos',
    name: 'Casino J',
    imgLink: './images/e10.png',
    percentage: '100%',
    "jusqu'a": "JUSQU'A",
    amount: '200€',
    spin_amount: '-',
    features: ["100% jusqu'à 200€", 'Bonus découverte 50€', 'Club privilège'],
    clr: '#2a243d',
    rating: './images/s1.svg',
    buttonLink: 'https://www.sos-casino.com/go/lucky8',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/lucky8',
    bgclr: '#edecf0',
    lancement: 2017,
    licence: 'Curaçao',
    depotmin: '10€',
    introduction: 'Welcome to Casino T!',
    wagering: '40x', // Odd id, updated
  },
  {
    id: 11,
    type: 'nouveauxCasinos',
    name: 'Casino K',
    imgLink: './images/e11.png',
    percentage: '100%',
    "jusqu'a": "JUSQU'A",
    amount: '300€',
    spin_amount: 150,
    features: ["100% jusqu'à 300€", '150 free spins', 'Bonus sans wager'],
    clr: '#f6456e',
    rating: './images/s3.svg',
    buttonLink: 'https://www.sos-casino.com/go/arlequin',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/arlequin',
    bgclr: '#ffffff',
    lancement: 2021,
    licence: 'Curaçao',
    depotmin: '10€',
    introduction: `Areqluin Casino possède plusieurs atouts susceptibles de satisfaire les joueurs, surtout s'ils sont amateurs de machines à sous.`,
    wagering: '0x', // Even id, updated
  },
  {
    id: 12,
    type: 'nouveauxCasinos',
    name: 'Casino L',
    imgLink: './images/e12.png',
    percentage: '100%',
    "jusqu'a": "JUSQU'A",
    amount: '100€',
    spin_amount: 100,
    features: ['100€ de bonus', '100 free spins', 'Programme de fidélité'],
    clr: '#1b3e55',
    rating: './images/s2.svg',
    buttonLink: 'https://www.sos-casino.com/go/alexander',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/alexander-casino',
    bgclr: '#edecf0',
    lancement: 2023,
    licence: 'Curaçao',
    depotmin: '10€',
    introduction: `Vivez une expérience de jeu mémorable aux côtés d'Alexandre le Grand !`,
    wagering: '30x', // Odd id, updated
  },
  {
    id: 13,
    type: 'casinos',
    name: 'Casino M',
    imgLink: './images/e13.png',
    percentage: '150%',
    "jusqu'a": "JUSQU'A",
    amount: '500€',
    spin_amount: 20,
    features: ["150% jusqu'à 500€", '20 Free Spins', '10% de cashback'],
    clr: '#d1d1d1',
    rating: './images/s2.svg',
    buttonLink: 'https://www.sos-casino.com/go/azur',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/azur',
    bgclr: '#ffffff',
    lancement: 2017,
    licence: 'Antillephone',
    depotmin: '10€',
    introduction: `Azur Casino offre un catalogue de jeux attractif, un service client attentif et des délais de paiement rapides.`,
    wagering: '20x', // Even id, updated
  },
  {
    id: 14,
    type: 'casinos',
    name: 'Casino N',
    imgLink: './images/e14.png',
    percentage: '100%',
    "jusqu'a": "JUSQU'A",
    amount: '100€',
    spin_amount: '-',
    features: ["100% jusqu'à 100€", '25% jusqu’à 200€', 'Live casino'],
    clr: '#192a1c',
    rating: './images/s2.svg',
    buttonLink: 'https://www.sos-casino.com/go/dublinbet',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/dublinbet',
    bgclr: '#edecf0',
    lancement: 2014,
    licence: 'Curaçao',
    depotmin: '10€',
    introduction:
      'Dublinbet revient sur le devant de la scène dans une version revisitée pour offrir le meilleur aux joueurs.',
    wagering: '30x', // Odd id, updated
  },
  {
    id: 15,
    type: 'casinos',
    name: 'Casino O',
    imgLink: './images/e15.png',
    percentage: '100%',
    "jusqu'a": "JUSQU'A",
    amount: '50€',
    spin_amount: 100,
    features: ['350€ de bonus', '100 free spins', 'Club VIP'],
    clr: '#150906',
    rating: './images/s2.svg',
    buttonLink: 'https://www.sos-casino.com/go/casinoextra',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/extra',
    bgclr: '#ffffff',
    lancement: 2013,
    licence: 'Curaçao',
    depotmin: '10€',
    introduction: `Casino Extra propose un catalogue de jeux très varié, parmi lesquels les titres de plusieurs éditeurs de renom.`,
    wagering: '30x',
  },
  {
    id: 16,
    type: 'casinos',
    name: 'Casino P',
    imgLink: './images/e16.png',
    percentage: '100%',
    "jusqu'a": "JUSQU'A",
    amount: '100€',
    spin_amount: '-',
    features: ["100% jusqu'à 100€", "31% jusqu'à 50€", 'Club VIP'],
    clr: '#d1d1d1',
    rating: './images/s2.svg',
    buttonLink: 'https://www.sos-casino.com/go/lucky31',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/lucky31',
    bgclr: '#ffffff',
    lancement: 2012,
    licence: 'Curaçao',
    depotmin: '10€',
    introduction: `Lucky 31 propose un large éventail de jeux de casinos développés par les leaders du secteur.`,
    wagering: '30x', // Even id, updated
  },
  {
    id: 17,
    type: 'casinos',
    name: 'Casino Q',
    imgLink: './images/e17.png',
    percentage: '200%',
    "jusqu'a": "JUSQU'A",
    amount: '200€',
    spin_amount: 20,
    features: ["200% jusqu'à 200€", '20 Free Spins', 'Bingo en ligne'],
    clr: '#d7d7d7',
    rating: './images/s2.svg',
    buttonLink: 'https://www.sos-casino.com/go/onlinebingo',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/online-bingo',
    bgclr: '#edecf0',
    lancement: 2007,
    licence: 'Curaçao',
    depotmin: '10€',
    introduction: `Online Bingo, qui jouit d’une excellente réputation, séduira incontestablement les amateurs de bingo.`,
    wagering: '30x', // Odd id, updated
  },
  {
    id: 18,
    type: 'casinos',
    name: 'Casino R',
    imgLink: './images/e18.png',
    percentage: '150%',
    "jusqu'a": "JUSQU'A",
    amount: '300€',
    spin_amount: 200,
    features: ["150% jusqu'à 300€", '200 free spins', 'Bonus exclusif'],
    clr: '#e97b65',
    rating: './images/s2.svg',
    buttonLink: 'https://www.sos-casino.com/go/banzaislots',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/banzai-slots',
    bgclr: '#ffffff',
    lancement: 2019,
    licence: 'Antillephone',
    depotmin: '10€',
    introduction: `Banzai Slots promet aux joueurs monts et merveilles, notamment avec ses bonus sans condition de mise.`,
    wagering: '0x', // Even id, updated
  },
  {
    id: 19,
    type: 'nouveauxCasinos',
    name: 'Casino S',
    imgLink: './images/e19.png',
    percentage: '100%',
    "jusqu'a": "JUSQU'A",
    amount: '800€',
    spin_amount: 150,
    features: ['1 500€ de bonus', '150 free spins', 'Bonus sans wager'],
    clr: '#040404',
    rating: './images/s4.svg',
    buttonLink: 'https://www.sos-casino.com/go/cabarino',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/cabarino',
    bgclr: '#edecf0',
    lancement: 2022,
    licence: 'Antillephone',
    depotmin: '10€',
    introduction: `Cabarino n'est ni dénué de charme visuel ni d'atouts promotionnels.`,
    wagering: '0x', // Odd id, updated
  },
  {
    id: 20,
    type: 'nouveauxCasinos',
    name: 'Casino T',
    imgLink: './images/e20.png',
    percentage: '120%',
    "jusqu'a": "JUSQU'A",
    amount: '1200€',
    spin_amount: 150,
    features: ['1 200€ de bonus', 'Cryptomonnaies', 'Paiement rapide'],
    clr: '#282828',
    rating: './images/s3.svg',
    buttonLink: 'https://www.sos-casino.com/go/tortuga',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/tortuga',
    bgclr: '#ffffff',
    lancement: 2021,
    licence: 'Curaçao',
    depotmin: '10€',
    introduction: `Cap sur l'île de Tortuga et son envoûtant capitaine, pour un dépaysement maximal !`,
    wagering: '40x', // Even id, updated
  },
  {
    id: 21,
    type: 'casinos',
    name: 'Casino E',
    imgLink: './images/e21.png',
    percentage: '100%',
    "jusqu'a": "JUSQU'A",
    amount: '500€',
    spin_amount: 25,
    features: [
      '1000€ de bienvenue',
      "Jusqu'à 100 free spins",
      '25% de cashback',
    ],
    clr: '#d14f76',
    rating: './images/s4.svg',
    buttonLink: 'https://www.sos-casino.com/go/evolve',
    buttonLinkTwo: 'https://www.sos-casino.com/casinos/evolve',
    bgclr: '#edecf0',
    lancement: 2023,
    licence: 'Antillephone',
    depotmin: '10€',
    introduction: `Ce casino en ligne possède un atout de poids : son catalogue de jeux, alimenté par plusieurs dizaines d'éditeurs.`,
    wagering: '25x', // Odd id, updated
  },
]
